/**
 * Serialize the browser assets into the text of
 * `packages/web/generated/client-bundle.ts`.
 *
 * The generated module is plain ECMAScript — `export const` string and number
 * literals and nothing else — so the same text parses and evaluates as
 * TypeScript under Deno and as a module under Node and Bun. Producing the
 * assets needs `deno bundle` and is therefore Deno-only
 * (`scripts/build-web-client.ts`); turning assets into module text touches
 * neither the filesystem nor the host, which is what lets every runtime's suite
 * exercise the generated module's contract.
 */

export function byteLength(text: string): number {
  return new TextEncoder().encode(text).length;
}

const PRINT_WIDTH = 100;

const SHORT_ESCAPES: Record<string, string> = {
  "\b": "\\b",
  "\t": "\\t",
  "\n": "\\n",
  "\f": "\\f",
  "\r": "\\r",
};

export function chooseQuote(content: string): '"' | "'" {
  let singleCount = 0;
  let doubleCount = 0;
  for (const char of content) {
    if (char === "'") {
      singleCount++;
    } else if (char === '"') {
      doubleCount++;
    }
  }
  return singleCount < doubleCount ? "'" : '"';
}

const LINE_SEPARATOR = 0x2028;
const PARAGRAPH_SEPARATOR = 0x2029;

function unicodeEscape(code: number): string {
  return `\\u${code.toString(16).padStart(4, "0")}`;
}

/** Escapable characters all fit in one UTF-16 code unit, so `charCodeAt(0)` never misclassifies. */
export function quoteString(content: string): string {
  const quote = chooseQuote(content);
  const out: string[] = [quote];
  for (const char of content) {
    const code = char.charCodeAt(0);
    if (char === "\\") {
      out.push("\\\\");
    } else if (char === quote) {
      out.push(`\\${quote}`);
    } else if (code === LINE_SEPARATOR || code === PARAGRAPH_SEPARATOR) {
      out.push(unicodeEscape(code));
    } else if (char in SHORT_ESCAPES) {
      out.push(SHORT_ESCAPES[char]);
    } else {
      out.push(code < 0x20 ? unicodeEscape(code) : char);
    }
  }
  out.push(quote);
  return out.join("");
}

export function constAssignment(name: string, quoted: string): string {
  const flat = `export const ${name} = ${quoted};`;
  return flat.length <= PRINT_WIDTH ? flat : `export const ${name} =\n  ${quoted};`;
}

export function generatedModule(clientJs: string, themeCss: string): string {
  return [
    "// GENERATED by scripts/build-web-client.ts — do not edit by hand.",
    "// Run `deno task build:web` to regenerate; not a repository source file.",
    "// See specs/release-process-spec.md and packages/web.",
    "",
    "/** The minified browser client bundle served as the form page's script. */",
    constAssignment("clientJs", quoteString(clientJs)),
    "",
    "/** The themed stylesheet, fonts embedded, served as the form page's stylesheet. */",
    constAssignment("themeCss", quoteString(themeCss)),
    "",
    "/** UTF-8 byte length of `clientJs`. */",
    `export const clientJsBytes = ${byteLength(clientJs)};`,
    "",
    "/** UTF-8 byte length of `themeCss`. */",
    `export const themeCssBytes = ${byteLength(themeCss)};`,
    "",
  ].join("\n");
}

const HEADER = "// GENERATED by scripts/build-web-client.ts";

/**
 * The shape `generatedModule` above always produces, read back.
 *
 * A reader that has to be cheap cannot evaluate 800 KB of module text every few
 * milliseconds, and does not need to: what a half-written or replaced file
 * looks like is a missing header, a missing assignment, or text that stops
 * before the last statement. The consumers import the module and check its
 * assets against their own recorded byte counts — that is the semantic half,
 * and it runs once per cycle rather than once per observation.
 */
export function incomplete(text: string): string | undefined {
  if (!text.startsWith(HEADER)) {
    return "the generated header is missing, so this is not the module a build publishes";
  }
  for (const name of ["clientJs", "themeCss"]) {
    if (!new RegExp(`export const ${name} =\\s*['"]`).test(text)) {
      return `\`export const ${name}\` is missing or is not a string literal`;
    }
    const recorded = new RegExp(`export const ${name}Bytes = (\\d+);`).exec(text);
    if (recorded === null) {
      return `\`export const ${name}Bytes\` is missing`;
    }
    if (Number(recorded[1]) === 0) {
      return `${name} is recorded as empty`;
    }
  }
  // The last statement `generatedModule` writes. Text that stops before it
  // stopped part way, however well-formed everything ahead of it looks.
  if (!/export const themeCssBytes = \d+;\n$/.test(text)) {
    return "the module does not end with its last statement, so it is partial";
  }
  return undefined;
}
