/**
 * Generate .github/workflows/publish-packages.yml from the workspace manifests.
 *
 * Usage:
 *   deno task gen:publish-workflow
 *
 * The orchestrator fans out one publish-one.yml call per @executablemd package,
 * ordered with `needs:` so dependencies publish before dependents. The set of
 * packages and their order are derived here from each member's deno.json (name)
 * and package.json (internal dependencies), so the workflow never drifts from
 * the manifests. CI fails if the committed file is stale (see ci.yml).
 */

import { exit, main } from "effection";
import { readTextFile, writeTextFile } from "@effectionx/fs";
import { z } from "npm:zod@^4";

const SCOPE = "@executablemd/";

const NamedSchema = z.object({ name: z.string() });
const DepsSchema = z.object({ dependencies: z.record(z.string(), z.string()).optional() });
const RootSchema = z.object({ workspace: z.array(z.string()) });

interface Member {
  dir: string;
  job: string;
  internal: string[];
}

const HEADER = `name: Publish packages

# GENERATED by scripts/gen-publish-workflow.ts — do not edit by hand.
# Run \`deno task gen:publish-workflow\` after adding/removing a workspace
# package or changing its @executablemd dependencies, then commit the result.
#
# One tag ships everything: release.yml builds the binary; this workflow fans
# out one publish-one.yml run per @executablemd package, ordered with \`needs:\`
# so dependencies publish before dependents (leaves run in parallel).
#
# Prerequisites (one-time) — see .github/PUBLISHING.md:
#   - npm: an OIDC trusted publisher per @executablemd package. The workflow
#     filename npm validates is the CALLER (publish-packages.yml), not the
#     reusable publish-one.yml. No npm token is used.
#   - JSR: create/link the @executablemd packages to this repo (best-effort).
#
# Note for consumers: core/runtime/cli depend on effection's 4.x prerelease,
# which npm's peer resolver rejects against @effectionx/* (\`^3 || ^4\`). Until
# effection 4 is stable, installing those packages needs \`--legacy-peer-deps\`.

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish (e.g. v0.2.0)"
        required: true

permissions:
  contents: read
  id-token: write # granted to the reusable publish-one.yml jobs for OIDC

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      value: \${{ steps.resolve.outputs.value }}
    steps:
      - id: resolve
        run: |
          TAG="\${{ github.event.inputs.tag || github.ref_name }}"
          echo "value=\${TAG#v}" >> "$GITHUB_OUTPUT"
`;

await main(function* () {
  const repoRoot = new URL("../", import.meta.url);
  const root = RootSchema.parse(JSON.parse(yield* readTextFile(new URL("deno.json", repoRoot))));

  const members: Member[] = [];
  for (const dir of root.workspace) {
    let denoText: string;
    let pkgText: string;
    try {
      denoText = yield* readTextFile(new URL(`${dir}/deno.json`, repoRoot));
      pkgText = yield* readTextFile(new URL(`${dir}/package.json`, repoRoot));
    } catch {
      continue;
    }
    const named = NamedSchema.safeParse(JSON.parse(denoText));
    if (!named.success || !named.data.name.startsWith(SCOPE)) {
      continue;
    }
    const deps = DepsSchema.parse(JSON.parse(pkgText)).dependencies ?? {};
    members.push({
      dir,
      job: named.data.name.slice(SCOPE.length),
      internal: Object.keys(deps)
        .filter((dep) => dep.startsWith(SCOPE))
        .map((dep) => dep.slice(SCOPE.length)),
    });
  }

  const publishable = new Set(members.map((member) => member.job));

  // Topological order: dependencies before dependents.
  const byJob = new Map(members.map((member) => [member.job, member]));
  const ordered: Member[] = [];
  const seen = new Set<string>();
  const visit = (member: Member): void => {
    if (seen.has(member.job)) {
      return;
    }
    seen.add(member.job);
    for (const dep of member.internal) {
      const target = byJob.get(dep);
      if (target) {
        visit(target);
      }
    }
    ordered.push(member);
  };
  for (const member of members) {
    visit(member);
  }

  const lines = [HEADER];
  for (const member of ordered) {
    const needs = ["version", ...member.internal.filter((dep) => publishable.has(dep))];
    lines.push(`  ${member.job}:`);
    lines.push(`    needs: [${needs.join(", ")}]`);
    lines.push("    uses: ./.github/workflows/publish-one.yml");
    lines.push("    with:");
    lines.push(`      package: ${member.dir}`);
    lines.push("      version: ${{ needs.version.outputs.value }}");
    lines.push("");
  }

  const out = new URL(".github/workflows/publish-packages.yml", repoRoot);
  yield* writeTextFile(out, lines.join("\n").trimEnd() + "\n");
  console.log(`generated .github/workflows/publish-packages.yml (${ordered.length} packages)`);
  yield* exit(0);
});
